### ISSUE TITLE
Redis commands hang indefinitely when Redis connection `ETIMEDOUT` (cannot be established)

### ISSUE THREAD

**Issue by ehsangifani** [adonisjs/redis#27]
## What happens
The adonisjs server is running.
Redis-server goes down.
client sends a request to `/key`
client will never receive a response (client browser waits for the response indefinitely)
## Package version
Adonis 4.1 (api only)
the version adonisjs installed: `adonis install @adonisjs/redis` : "@adonisjs/redis": "^2.0.7"

## Node.js and npm version
Node v12.18.1
yarn 1.22.4 (project setup with --yarn)
npm 6.14.5

## Sample Code (to reproduce the issue)
Every config is on its default\
app/Http/KeyController.js:
```js
class KeyController {
	async index({ request, response }) {
		try {
			const value = await Redis.get("mykey");
			if (value) {
				return response.send({ value });
			}
			return response.notFound();
		} catch (err) {
			return response.status(500).send({ error: err.toString() });
		}
	}
}
```

Add `Route.get("key", "KeyController.index");` to start/routes.js 

What is also annoying is that there will be many tries to connect and therefore many error lines in console about 
`[ioredis] Unhandled error event: Error: connect ETIMEDOUT`
But there is no way to handle it [`Redis.on("error", (err) => {//handling...
})` does not work ]

So is there any workaround on how to send a response to the client when this condition happens?

**Comment by thetutlage** [comment]
If redis client is having trouble making the connection, then shouldn't you be checking server connectivity?
