### ISSUE TITLE
Version 7 seems like incompatible with AdonisJS 4.1

### ISSUE THREAD

**Issue by flatdragon** [adonisjs/redis#31]
## Versions
**@adonisjs/cli version:** 4.0.12
**Node.js version:** 14.16.0
**NPM version:** 6.14.11

## Steps to reproduce
1. Start with fresh environment;
2. Install AdonisJS CLI;
`npm install -g @adonisjs/cli`
3. Init new project via CLI;
`adonis new project`
4. Enter new project directory;
`cd project`
5. Install Redis package via CLI;
`adonis install @adonisjs/redis`
6. Put "@adonisjs/redis/providers/RedisProvider" to "start/app.js" providers;
7. Check out problems that listed below.

## Problem 1
After installation Redis config doesn't appear inside "config" directory.

## Problem 2
After run:
`adonis serve --dev`
Got error:
![adonis-redis-issue](https://user-images.githubusercontent.com/27871540/113014022-70eb4e80-91a6-11eb-9ce3-e3c6e4d6bda6.PNG)

## NOTE
Version 7 is installed by CLI, not manually. Probably TypeScript causes this issue.

**Comment by RomainLanz** [comment]
Hey @flatdragon! 👋 

If you are using AdonisJS 4.1, you need to use the `@legacy` tag to install a package.

```bash
npm i @adonisjs/redis@legacy
```

**Comment by flatdragon** [comment]
Hi! Thank you very much. Issue with provider is fixed.

However, what about CLI behavior? I suppose it should then install "@adonisjs/redis@legacy" instead of "@adonisjs/redis:^7.0.0".

I mean that "npm i @adonisjs/redis@legacy" won't auto-publish config file. It's not a big deal to copy it manually, but just wanna inform about this issue, to keep behavior that was described in docs:
https://adonisjs.com/docs/4.1/redis#_setup

**Comment by thetutlage** [comment]
Yes. Already working on the fix :)

**Comment by flatdragon** [comment]
Just tried out "adonis install @adonisjs/redis@legacy". Installation successfully finished, but config still missing.

Okey, thanks! Have a nice day guys.

**Comment by RomainLanz** [comment]
Can you please update `@adonisjs/cli` and try again?

**Comment by flatdragon** [comment]
Yep. It's fine for now. Thanks.
![adonis-redis-issue-2](https://user-images.githubusercontent.com/27871540/113027821-b6af1380-91b4-11eb-936d-96a3729b8597.PNG)

**Comment by RomainLanz** [comment]
Cool, perfect then!
