### ISSUE TITLE
Subscribe always return "null" for message.

### ISSUE THREAD

**Issue by antt0n** [adonisjs/redis#36]
Hello,
I have a problem that I did not encounter in the past.
It seems that the subscribe to a channel returns me all the time `null`.
The connection to Redis works, especially since `null` is only sent when new content is sent through the channel.

## Package version
7.0.2

## Node.js and npm version
NodeJS: 6.14.13
NPM: 14.17.0

## Sample Code (to reproduce the issue)
```JS
Redis.subscribe('test', (message: string) => {
    console.log(message)
})
```

**Comment by thetutlage** [comment]
Published. Please install the latest version `7.0.3`

**Comment by antt0n** [comment]
Thank you very much for your responsiveness !
