### ISSUE TITLE
Publish: a way to disable the MessageBuilder

### ISSUE THREAD

**Issue by antt0n** [adonisjs/redis#37]
Hello,
A very small and practical feature.
Would it be possible to add a way to remove the MessageBuilder from the publish (by an argument for example)?
Thanks in advance!

**Comment by thetutlage** [comment]
Can you share the use case?

**Comment by antt0n** [comment]
Yes, in an environment using a different message format, this update prevents the normal operation of the infrastructure. I am upgrading an application that was on the alpha version of Adonis, and the MessageBuilder would force me to upgrade all the pub/sub system on my applications to support the new system.

**Comment by thetutlage** [comment]
I think the MessageBuilder is creating more issues than providing any help. Also this is not a documented feature, so we can just get rid of it altogether and use string based messages only

**Comment by antt0n** [comment]
I think it's a good idea.
It makes it easier to integrate a pub/sub, knowing that you don't necessarily need to know where the message is coming from.
In any case, it is quite easy to make your own "MessageBuilder".

**Comment by thetutlage** [comment]
Can you submit a PR for the same?

**Comment by antt0n** [comment]
After more thought, I wonder if it wouldn't be better to keep the MessageBuilder system, but maybe in a different method?
Because it could be convenient to connect different Adonis instances to each other, and have this verification system (let's say it's easier to use, and it can be a good way to establish a standard for communications with Redis pub/sub in Adonis environments).
Especially since there is nothing to prevent future applications from taking advantage of this way of doing things.
What do you think about it?
Maybe it's better to move the current `publish` method under the name `mbpublish` (for MessageBuilderPublish) ?

**Comment by thetutlage** [comment]
I think it will be better to remove it vs overloading the API with too many methods. The message builder was used just for serializing the messages from JavaScript data types to JSON. But I think, no one has ever complained for passing strings in pub/sub, so it was an unnecessary improvement, that did more harm than good

**Comment by thetutlage** [comment]
Removed in https://github.com/adonisjs/redis/commit/c488b42308f74965ccb7893bcc311a3e6ae4693a

**Comment by thetutlage** [comment]
https://github.com/adonisjs/redis/releases/tag/v7.0.4
