### ISSUE TITLE
subscribing bug using socketio-redis-adapter and adonis/redis connection

### ISSUE THREAD

**Issue by davidlandais** [adonisjs/redis#39]
## Package version
7.1.0

## Node.js and npm version
16.x and 8.x

## External Dependencies
https://github.com/socketio/socket.io 4.4.0
https://github.com/socketio/socket.io-redis-adapter 7.1.0
https://github.com/socketio/socket.io-redis-emitter 4.1.1

## Issue description
To bring realtime in my application, I want to use Socket.IO as my websocket provider.
To do so, I create an instance of SocketIO "Server" and put AdonisServer.instance as first argument.
All is working correctly. I can connect to the websocket from my VueJS client.

To be able to work with multiple instance of adonis (like for example, 3 instances in heroku), I'm using the pkg "socket.io-redis-adapter". This pkg, will use the Redis pub/sub mechanism. Each instance of SocketIO.Server listening in each AdonisServer will connect to the my Redis instance and pub/sub to a channel named "socket.io" (default name). I configured 3 connections in adonis - redis.conf (publisher, subscriber, emitter).
![broadcasting-redis](https://user-images.githubusercontent.com/2110040/148225226-f864d39e-a257-4b97-8dc6-3d2581d0f7e7.png)

Then, for cron jobs, I decided to make a command in adonis. This one will use the pkg "socket.io-redis-emitter". This pkg, help to communicate to each SocketIO.Server connected to the redis instance by publishing a message to the socket.io channel. Then each SocketIO adapters, will receive the message and broadcast this last to each socket connected.
![redis-emitter](https://user-images.githubusercontent.com/2110040/148225242-c0a9f45c-8a17-4336-b837-767ba153bc90.png)

The problem seems to be located in the subscriber client in the adapter and linked to your abstracted subscribe implementation. The subscriber does not seems to receive the published message.

**Comment by davidlandais** [comment]
Ok, the problem is not located on publish. Reading your code, you are bringing publish in the abstract class.
The problem is located on the subscriber client in the redis-adapter. Finally, without using "ioConnection" in the publisher and the emitter is working. But when not using "ioConnection" in the subscriber this isn't working.

**Comment by thetutlage** [comment]
Not sure if I am missing something here. But socketio-redis-adapter has nothing to do with this repo

**Comment by thetutlage** [comment]
Closing since not actionable
