### ISSUE TITLE
Upgrade to ioredis 5.0.2 version

### ISSUE THREAD

**Issue by sumanadak** [adonisjs/redis#45]
Dear,

How can I upgrade to ioredis 5.0.2 version as there is a bug fix(https://github.com/luin/ioredis/issues/1536) in typescript declaration for hmset command which is required for my adonisjs application .

Please help me on this.

Thanks
Suman

**Comment by RomainLanz** [comment]
Closing.

https://github.com/adonisjs/core/discussions/3653
