### ISSUE TITLE
Typecheck errors in typescript strict mode

### ISSUE THREAD

**Issue by devotox** [adonisjs/redis#48]
## Summary
When adding strict mode to tsconfig.json we encounter errors in typechecking as the redis config types cannot be found

## Package version
7.3.0

## Node.js and npm version
Node: 16.15.1
NPM: 8.11.0

## Sample Code (to reproduce the issue)
```
npx create-adonis-ts-app hello-world
cd hello-world
npm i @adonisjs/redis
node ace configure @adonisjs/redis

---- add strict to tsconfig.json
----- run a tsc typecheck
```

**Comment by Julien-R44** [comment]
Fixed in #49
