### ISSUE TITLE
Patch redis config in runtime

### ISSUE THREAD

**Issue by estermer** [adonisjs/redis#51]
In my use case I am creating new clients in AWS and need to update the application redis configuration to add them during run time.

We can do this with `Database.patch()` for Lucid in adonis for multi tenant databases, but I think it would be nice to do this with Redis, but I cannot find documentation on how to accomplish this.

This would be a nice to have so I don't have to reset my app to connect to my new tenant's redis client.

**Comment by thetutlage** [comment]
You want to add new config/create connection on the fly. Or you want to patch the config of an existing connection and re-establish the connection?
