### ISSUE TITLE
Can't use Redis as session storage

### ISSUE THREAD

**Issue by drajathasan** [adonisjs/redis#55]
## Package version

@adonisjs/redis version "^7.3.2"

## Node.js and npm version

node : v18.12.1
npm : 8.19.2

## Sample Code (to reproduce the issue)

.env file
![image](https://user-images.githubusercontent.com/38057222/210125732-d6af2aad-7164-4b9e-8489-4733e64d69ed.png)
config/session.ts
![image](https://user-images.githubusercontent.com/38057222/210125804-c8c2728c-2e22-47bd-bad5-f8623e940e9d.png)
config/redis.ts
![image](https://user-images.githubusercontent.com/38057222/210125853-1110ea56-bd7a-4560-a5a3-ea15df7ad919.png)
package.json
![image](https://user-images.githubusercontent.com/38057222/210126038-fb18c517-e9c4-4398-ad4f-ff1ad1b6a818.png)

## BONUS (a sample repo to reproduce the issue)
I got error like this
![image](https://user-images.githubusercontent.com/38057222/210125997-50b92f1d-e503-47ab-940c-0f8bc88fb2fd.png)

**Comment by RomainLanz** [comment]
Hey @drajathasan! 👋🏻

Ensure that the `redis` provider is registered before the `session` provider inside the `.adonisrc` file.
If that still doesn't work, create a repository with the minimum amount of code to reproduce your issue.
