### ISSUE TITLE
Error when running the configure command

### ISSUE THREAD

**Issue by abiliocoelho** [adonisjs/redis#60]
### Package version

8.0.0

### Describe the bug

 Error: Package subpath './package.json' is not defined by
   "exports" in
   /Users/abiliocoelho/www/projects/smileCare/api/node_modules/@adonisjs/redis/package.json

**Comment by martinkihuha** [comment]
I have a similar issue when I try to run **node ace configure @adonisjs/redis** I get the error below:

Error: Package subpath './package.json' is not defined by "exports" in
   /<ADONISJS_APP_PATH>/node_modules/@adonisjs/redis/package.json

**Comment by Julien-R44** [comment]
Please rollback to version ^7.3.4. 
Version 8.0.0 is for Adonis 6 only.
