### ISSUE TITLE
Support Connection via Socket File

### ISSUE THREAD

**Issue by marcuspoehls** [adonisjs/redis#67]
### Package version

8.0.1

### Describe the bug

I’m attempting to run an Adonis application on [Uberspace](https://uberspace.de/en). The Uberspace hosting offers Redis but connections must use a `sock` file. Here’s a link to their Redis guide: https://lab.uberspace.de/guide_redis/

The `@adonisjs/redis` package currently uses a Redis configuration file that requires an object when configuring a Redis connection. I couldn’t find a connection config key that allowed me to pass a socket path for the connection. The underlying [ioredis](https://github.com/redis/ioredis?tab=readme-ov-file#connect-to-redis) package supports socket files for connections.

Am I missing something and are socket connections already possible with this package?

**Comment by marcuspoehls** [comment]
I went through all options of an `ioredis` connection configuration object again and found the `path` key. That solves the issue 🙂 

Here’s a simplified Redis config file for reference (`config/redis.ts`):

```ts
const redisConfig = defineConfig({
  connection: 'main',

  connections: {
    main: {
      path: env.get('REDIS_SOCKET_PATH'),
      host: env.get('REDIS_HOST'),
      port: env.get('REDIS_PORT'),
      password: env.get('REDIS_PASSWORD', ''),
      db: 0,
      keyPrefix: env.get('REDIS_KEY_PREFIX', ''),
      retryStrategy (times) {
        return times > 10 ? null : times * 50
      },
    },
  },
})
```

The configuration above allows us to use Redis via host/port during development and a Socket file in production. It seems that ioredis ignores host/port if the `path` option is present and not empty.

**Comment by marcuspoehls** [comment]
For reference, here’s the ioredis options list I mentioned
https://ioredis.readthedocs.io/en/latest/API/

**Comment by thetutlage** [comment]
Can you please create a PR in the docs to mention the usage of Socket path? I think it will be a common use-case for many

**Comment by marcuspoehls** [comment]
Good point. I'll submit a PR to the docs repo. Eta: by the end of the week 🙂
